---
abstract: 'Distribution kwalitee tests in one command'
author:
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::If: 0
  Test::More: 0
  Test::NoWarnings: 0
  lib::abs: 0.90
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Dist
no_index:
  directory:
    - inc
    - t
provides:
  Test::Dist:
    file: lib/Test/Dist.pm
    version: 0.01
requires:
  Array::Diff: 0
  ExtUtils::MakeMaker: 0
  ExtUtils::Manifest: 0
  Module::CPANTS::Analyse: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
